### PR TITLE
AlphaNetworks SNQ60A0-320F and SNX60A0-486F: add kernel patch to mask th...

### PR DESCRIPTION
**Pull request by willkuo103**
...e useless error message

### CODE REVIEW

**Comment by cbrune** [comment]
I think this fix OK.

However the commit message is a little terse.  Please review the ONIE developer's guide about patching:
https://opencomputeproject.github.io/onie/docs/developers/contributing.html#general-patching-philosophy

Particularly item 2:
```
2. Each patch must have the following:

-The author must be a real person with a valid email address. No anonymous github user IDs.

-A short one line summary. When the patch is for a specific machine include the machine name or company as a prefix to the summary, e.g. “machine_xyz_123: updated installer config”.

- What problem the patch solves (why do we need the patch).

- How you tested the patch.
```

In this case your commit message contains a *long* one line summary.  Please keep the one line summary to around 80 characters.  Then put the details about the problem and why you are fixing it in the body of the commit message paragraphs.

**Comment by willkuo103** [comment]
Hi Curt,

Thanks for your instruction. I have modified the commit message. Please let me know if there is any problem.

Thanks,
Will

**Comment by cbrune** [comment]
Hmmm.  I'm not seeing the updated message.  I see this:

```
linux: $ git show
commit 466d4d1d546200b189c595a1d75d028e235272a8
Author: Will Kuo <will_kuo@alphanetworks.com>
Date:   Fri Mar 13 10:52:53 2015 +0800

    AlphaNetworks SNQ60A0-320F and SNX60A0-486F: patch kernel to prevent IGB driver display error message from unused SGMII interface
```

There is still just one long line of summary...  Please keep the one line summary to around 80 characters. Then put the details about the problem and why you are fixing it in the body of the commit message paragraphs.

**Comment by willkuo103** [comment]
Hi Curt,

I have modified the commit message again, please check and let me know if there is any problem.

Thanks,
Will

**Comment by cbrune** [comment]
Looks great.  Pushed to master:

- 8f3cd29 AlphaNetworks platforms: patch kernel to prevent from displaing the error message

**Pull request closed without merging**
