### PR TITLE
Add CLS DS4101 platform

### PR DESCRIPTION
**Pull request by nicwu-cel**
- Why I did it
Add CLS DS4101 platform

CPU: Xeon-D 4Core CPU D1627/Xeon-D 8Core CPU D1649N
RAM: 2x 16GB DDR4/16GB DDR4
SSD: 64GB/128GB/256GB M.2 SSD
Switch ASIC: TH4-100G Switch IC, BCM56996
Ethernet Port: 800G OSFP port x 32 and 10G SFP+ x 2
PHY: Intel I210
PSU: 2x AC PSU 2000W, hotswappable
Cooling: 6+1 fan-tray modules, hotswappable
Airflow: F2B airflow
BMC: W/
Dimension: 438.5mm(W)x43.1mm(H)x657.5mm(D)
Linux kernel version: 5.4.40
- How I did it
Add CLS DS4101 platform
- How I verified it
[log.txt](https://github.com/user-attachments/files/16454901/log.txt)

### CODE REVIEW

**Comment by nicwu-cel** [comment]
@cbrune

I would appreciate it if you could help review this pull request.

Looking forward to hearing from you soon.

Best Regards!

**Comment by mshych** [comment]
Hi, 
There are 2 platforms in this PR: cls_ds4101 and ces_ds4101.
Just one platform is mentioned in commit CLS DS4101. Please correct and describe a difference.
Different platforms should be added by different commits and not in one.

Thank you.

**Comment by nicwu-cel** [comment]
Hi @mshych,

The cls_ds4101 and cel_ds4101 are identical, they are only forward compatible for customer use. 
Should I add those platforms by 2 commits or I can describe this difference in the description?

Looking forward to your suggestions, thanks a lot.

**Comment by mshych** [comment]
Hi,
The content of cls_ds4101 and cel_ds4101 are completely the same.
What do you mean by "forward compatible" in this case?

**Comment by nicwu-cel** [comment]
> Hi, The content of cls_ds4101 and cel_ds4101 are completely the same. What do you mean by "forward compatible" in this case?

The platform cel_ds4101 is currently in use by our customers and will be rebranded to cls_ds4101. To ensure a seamless transition, we will temporarily submit both platforms.

**Comment by mshych** [comment]
Hi, But you don't make rebranding of already supported cel_ds4101 system to new cls_ds4101.
You add 2 completely similar systems.
You can add just new cls_ds4101 if as you wrote cel_ds4101 is already somehow in use.

**Comment by nicwu-cel** [comment]
Hi @mshych,

Okay, I will delete the cel_ds4101 and only keep the cls_ds4101 platform.

**Comment by mshych** [comment]
Just add pls your system to build-config/scripts/onie-build-targets.json

**Comment by nicwu-cel** [comment]
Hi @mshych,

Thank you for the reminder. I have updated the onie-build-targets.json file. Would you be able to review it at your earliest convenience?

**Comment by mshych** [comment]
Pushed to master.
Thank you for commit.

**Pull request closed without merging**
