### PR TITLE
Add ls1088ardb support, and update uboot and kernel for ls series platform

### PR DESCRIPTION
**Pull request by ZhaoQiang-b45475**
Add ls1088ardb support with uboot 2017.07 and kernel 4.9.79.
Update uboot to 2017.07 and kernel to 4.9.79 on ls1043ardb, ls2088ardb and ls1046ardb.

### CODE REVIEW

**Comment by cbrune** [comment]
This all looks good to me.  Nice to see the move forward to the latest default kernel.

Pushed to master:
- 319ddc7 machine: nxp_ls1043ardb: update kernel to 4.9.79 and uboot to 2017.07
- 3bc1fe3 machine: nxp_ls2088ardb: update kernel to 4.9.79 and uboot to 2017.07
- 4a15102 machine: nxp_ls1046ardb: update kernel to 4.9.79 and uboot to 2017.07
- f8c37d0 machine: nxp_ls1088ardb: add ls1088ardb support
- 8e1fc0b busybox: fw_env: modify crc size in getenvsize
- 8794be7 onie-mk-bin: add contiguous-uboot_ubootenv-up support
- 9ef7b8e support u-boot 2017.07

**Comment by cbrune** [comment]
I just noticed the nxp_ls1043ardb machine does not compile.  I get this:
```
make -j24 MACHINEROOT=../machine/nxp MACHINE=nxp_ls1043ardb VENDOR_REV=ONIE all demo
....
make[1]: *** No rule to make target 'conf/kernel/4.9.79/linux.armv8a.config', needed by '/work/marvel-07/onie-build/ci/master/onie/build/nxp_ls1043ardb-r0/kernel/linux/.config'.  Stop.
```

The file `build-config/conf/kernel/4.9.79/linux.armv8a.config` is missing from this pull request.  Reopening.

**Comment by ZhaoQiang-b45475** [comment]
Sorry for that, I have rebased and added "build-config/conf/kernel/4.9.79/linux.armv8a.config", Please review.

**Comment by cbrune** [comment]
Thanks!  Pushed to master:

- 6bc0866 armv8: add linux.armv8a.config to linux 4.9.79

**Pull request closed without merging**
