### PR TITLE
UEFI: initial support for ONIE on UEFI

### PR DESCRIPTION
**Pull request by cbrune**
This wide ranging patch encompasses refactoring and enhancements to
the core ONIE operations to support UEFI firmware and legacy BIOS
firmware.

The following ONIE components are updated are part of this patch:

- build system
- Linux kernel config (add EFI support)
- ONIE installer
- ONIE boot up
- ONIE OS uninstaller
- ONIE DEMO OS
- ONIE DEMO-DIAG OS
- ONIE / DEMO-OS interop
- ONIE / DEMO-DIAG interop

Testing Done:

Used the KVM virtual machine, the .ISO ONIE installer image, the demo
OS and demo DIAG OS to exercise the core ONIE operations.

  - install
  - rescue
  - uninstall
  - update
  - embed

The core operations were exercised in the following cases:

  - blank box, nothing installed
  - only the demo DIAG OS installed
  - only the demo OS installed
  - both the demo OS and demo DIAG installed

All of the above test cases were exercised for both legacy BIOS
firmware and UEFI firmware.

### CODE REVIEW

**Comment by cbrune** [comment]
For the multiple ONIE boot entry problem -- can you describe how to reproduce that exactly?  If I'm reading it right you did something like this:

1. boot ISO from USB
1. embedded ONIE
1. reboot
1. boot ISO from USB
1. embedded ONIE
1. reboot
1. boot ISO from USB
1. embedded ONIE
1. reboot
...

Is that how you got to the duplicate entries?

**Comment by cbrune** [comment]
For the eUSB boot entry problem -

I used a KVM and also a physical machine for testing.  What I see when I installed ONIE on a physical machine in the firmware boot menu looked like:
```
Boot Option Priorities
Boot Option #1          [ONIE: Open Netwo...]
Boot Option #2          [A0S0 ATP IG CFast...]
Boot Option #3          [[UEFI: IP4 Intel(R)]
Boot Option #4          [UEFI: Built-in EFI ...]

Hard Drive BBS Priorities
Network Device BBS Priorities
```

That is to say the output of `efibootmgr` matched what the UEFI firmware boot menu displayed.

I'm not sure why yours is behaving differently.

Are you sure ONIE installed without errors?  I am wondering if the install was really successful.
Can you inspect the output of:
```
ONIE:/ # blkid
ONIE:/ # sgdisk -p /dev/sda
ONIE:/ # find /boot/efi
```

If the firmware can't detect the EFI System Partition (ESP) then those items may not show up in the firmware's boot menu.

**Comment by david56** [comment]
> boot ISO from USB
>     embedded ONIE
>     reboot
>     boot ISO from USB
>     embedded ONIE
>     reboot
>     boot ISO from USB
>     embedded ONIE
>     reboot ...
> 
> Is that how you got to the duplicate entries?

Yes, the steps are the same as you said.

**Comment by david56** [comment]
The ``ONIE: Open Network Install Environment`` boot option is present now.  I erased the head 512 bytes in eUSB mass storage via ``dd if=/dev/zero of=/dev/sda bs=512 count=1`` and then re-installed UEFI ONIE.

    Boot Option Priorities
    Boot Option #1          [ONIE: Open Network ...]
    Boot Option #2          [UEFI: JetFlashTrans...]
    Boot Option #3          [JetFlashTranscend 8...]
    Boot Option #4          [IBA GE Slot 00A0 v1543]
    Boot Option #5          [UEFI: Built-in EFI ...]
    
    Network Device BBS Priorities
    Hard Drive BBS Priorities

ONIE can boot via UEFI firmware successfully!

    ONIE:/ # blkid
    /dev/sdb1: UUID="C64E-024F"
    /dev/sdb: LABEL="ONIE_RECOVERY"
    /dev/sda2: LABEL="ONIE-BOOT" UUID="03eebabd-61d9-48ff-930c-143b66484d7e"
    /dev/sda1: LABEL="EFI System" UUID="43D6-F142"
    ONIE:/ # sgdisk -p /dev/sda
    Disk /dev/sda: 15724544 sectors, 7.5 GiB
    Logical sector size: 512 bytes
    Disk identifier (GUID): 36AE9994-68C6-42B6-BA0A-3A921C950732
    Partition table holds up to 128 entries
    First usable sector is 34, last usable sector is 15724510
    Partitions will be aligned on 2048-sector boundaries
    Total free space is 14938045 sectors (7.1 GiB)
    
    Number  Start (sector)    End (sector)  Size       Code  Name
       1            2048          526335   256.0 MiB   EF00  EFI System
       2          526336          788479   128.0 MiB   3000  ONIE-BOOT
    ONIE:/ # find /boot/efi/
    /boot/efi/
    /boot/efi/EFI
    /boot/efi/EFI/onie
    /boot/efi/EFI/onie/grubx64.efi

It looks erasing mass storage shall be done at first time of changing BIOS to UEFI system.  After that, it can switch to each other between UEFI and BIOS without doing erasion.

It also has ``efibootmgr`` warning to refer duplicate ONIE boot entries.

    ONIE-RECOVERY:/ # onie-self-update -e /lib/onie/onie-updater
    discover: Rescue mode detected. No discover stopped.
    ONIE: Executing installer: /lib/onie/onie-updater
    Verifying image checksum ... OK.
    Preparing image archive ... OK.
    ONIE: Version       : 2015.5.21-dirty
    ONIE: Architecture  : x86_64
    ONIE: Machine       : accton_as6712_32x
    ONIE: Machine Rev   : 0
    ONIE: Config Version: 1
    Installing ONIE on: /dev/sda
    sd 6:0:0:0: [sda] No Caching mode page found
    sd 6:0:0:0: [sda] Assuming drive cache: write through
    sd 6:0:0:0: [sda] No Caching mode page found
    sd 6:0:0:0: [sda] Assuming drive cache: write through
    sd 6:0:0:0: [sda] No Caching mode page found
    sd 6:0:0:0: [sda] Assuming drive cache: write through
    ** Warning ** : Boot0000 has same label ONIE: Open Network Install Environment
    ** Warning ** : Boot0005 has same label ONIE: Open Network Install Environment
    ** Warning ** : Boot0006 has same label ONIE: Open Network Install Environment
    ** Warning ** : Boot0007 has same label ONIE: Open Network Install Environment
    ** Warning ** : Boot0008 has same label ONIE: Open Network Install Environment
    ** Warning ** : Boot0009 has same label ONIE: Open Network Install Environment
    ** Warning ** : Boot000A has same label ONIE: Open Network Install Environment
    Rebooting...

**Comment by cbrune** [comment]
That's great you have the UEFI booting up.

That is strange about the duplicate boot entries.  I will try to reproduce that using the method you describe.

**Comment by cbrune** [comment]
I could not reproduce the issue you described.

I think the best thing here is to get the changes into master and then fix problems from there.  Otherwise the patches get stale and are hard to maintain.

Pushed to master:

- 42c7448 UEFI: initial support for ONIE on UEFI

Also updated the kernel version used by the KVM machine to 4.0.4 for the latest UEFI support:

- a16e630 kvm_x86_64 vm: Update INSTALL instructions for UEFI
- 0bb890f kernel.org download url: allow for 4.x kernels
- 1802b51 kvm_x86_64: upgrade kernel to 4.0.4

**Pull request closed without merging**
