### PR TITLE
Wnc 20160304

### PR DESCRIPTION
**Pull request by vic1231**
These file are added for build ipmitool package. Some configs are opened:
1. uclibc config, check the diff with "build-config/arch/x86_64.make". Some network function needed with ipmitool.
2. linux kernel configs, check the diff with "machine/wnc/wnc_sst1_n1/kernel/config". The IPMI message handler needs be turn on.

Usage:
Add IPMITOOL_ENABLE = yes in machine.make. The default value is "no", located in "build-config/arch/x86_64.make".
And this package can be build with make parameter "all".
e.g., make MACHINEROOT=../machine/wnc MACHINE=wnc_sst1_n1 all recovery-iso

### CODE REVIEW

**Comment by cbrune** [comment]
This is all looks pretty reasonable.

Some of the patches need a little clean up and reorganization before going into the repo.  See the comments in the patches.

**Comment by cbrune** [comment]
Patch reorg - at high level we need to keep "core ONIE" patches separate from "machine specific" patches.  Within those two categories try to make one patch for each "logical" change.

With that in mind the final patch set should only contain 3 patches:

- one patch that adds all the core changes relating to adding the ipmi package, including files from build-config and the sha1 file.

- one patch that updates uClibc, commit 612b2ef

- one patch that updates the wnc_sst1_n1 machine files

**Comment by vic1231** [comment]
Hi Curt:
Did you mean that I should separate these 8 committed files into 3 new branches and pull them again?
And content of 3 new branches will looks like below?
1. machine specific:
machine/wnc/wnc_sst1_n1/machine.make
machine/wnc/wnc_sst1_n1/kernel/config
2. Core ONIE:
build-config/make/ipmitool.make
upstream/ipmitool-1.8.15.tar.bz2.sha1
build-config/Makefile
build-config/arch/x86_64.make
build-config/make/images.make
3. uclibC update:
build-config/conf/uclibc/0.9.33.2/uclibc.x86_64.config

With my machine pull request. Did you mean that I should add more details like
wnc_sst1_n1: updated machine makefile and kernel config for ipmitool?
Or this commit needs more details like describe machine feature or why this machine needs ipmitool?

**Comment by cbrune** [comment]
> Did you mean that I should separate these 8 committed files into 3 new branches and pull them again?

Yes, I mean make 3 patches and submit them in one pull request.

>And content of 3 new branches will looks like below?
1. machine specific:
machine/wnc/wnc_sst1_n1/machine.make
machine/wnc/wnc_sst1_n1/kernel/config
2. Core ONIE:
build-config/make/ipmitool.make
upstream/ipmitool-1.8.15.tar.bz2.sha1
build-config/Makefile
build-config/arch/x86_64.make
build-config/make/images.make
3. uclibC update:
build-config/conf/uclibc/0.9.33.2/uclibc.x86_64.config

Yes.

> With my machine pull request. Did you mean that I should add more details like
wnc_sst1_n1: updated machine makefile and kernel config for ipmitool?
Or this commit needs more details like describe machine feature or why this machine needs ipmitool?

I mean the comment for patches should not have one long run one line of text.  The first line is a short summary (~70 characters), then two blank lines and then the bulk of the description.

**Pull request closed without merging**
