### PR TITLE
ONIE GRUB support u-boot-like boot commands

### PR DESCRIPTION
**Pull request by david56**
The patchset intends to make ONIE GRUB:

1. Support u-boot-like boot commands that are useful for auto test programs.
2. Support boot command feeded by DIAG/NOS installer that can easily chage boot target between ONIE, DIAG and NOS.

The patchset is compatible with present DIAG/NOS installers.

### CODE REVIEW

**Comment by cbrune** [comment]
Hi @david56,

This is a big change and will take some time to digest.  I can't just read it and figure it all out.

I will spend some time this week loading this change on a box and try it out.

Have you tried running the OCE test suite?

@cobracmder - it would be nice if an additional set of eyes also kicked the tires on this one.

**Comment by cobracmder** [comment]
@cbrune copy that

**Comment by david56** [comment]
@cbrune I haven't done it yet. But I did several test cases combined with demo OS, demo DIAG, ONIE (install, rescue, uninstall, update, embed, and recovery ISO), onie-boot-mode, PC BIOS, and UEFI.

**Comment by cobracmder** [comment]
Hey @david56,

So these changes look interesting as they get closer to a UEFI type boot manager in ONIE. (FYI, if you can't tell, I'm a fan of UEFI and how it handles OS boot management.)

After running some OCE tests in KVM and on a 5712, I don't see any issues except when I run ```test-nos.sh``` with a production NOS (not demo OS) and ONL.

In order to use these new features, it requires NOS vendors to update their installers.  This can be done at their discretion for new versions.  But if a user is running a non-updated installer/installation and updates ONIE that includes these changes; they do not see the added benefit.

What are your thoughts on how to handle this case?

**Comment by david56** [comment]
Hello @cobracmder,

Thanks for running tests on the patchset!

UEFI boot manager is really useful for changing the boot sequence between partitions.  I also like it.  The patchset enhances ONIE managing boot order on PC BIOS and UEFI that makes the both boot management more closer.

> In order to use these new features, it requires NOS vendors to update their installers. This can be done at their discretion for new versions. But if a user is running a non-updated installer/installation and updates ONIE that includes these changes; they do not see the added benefit.
> 
> What are your thoughts on how to handle this case?

Yes, you are right.  It is necessary to revise NOS installer to support the new features.

In current ONIE design, NOS installer has to install a copy of GRUB on its own partition for chainloading.  It also has to set NOS partition to be the first boot order in the UEFI situation.  ONIE can not stop the operations from installation.  So that it will go for the present boot approach naturally.

**Comment by cbrune** [comment]
Hello @david56 -

There are quite a few proposed changes here and it has taken me some time to test them out and get my head wrapped around them.  What I did was compare the new behaviours to the old behaviours using the a 2015.11 version.  I think I understand most of what you are doing here.

My following comments are only about the legacy BIOS implementation.  I did not test or look at the UEFI implementation yet.

Definitely there are some great ideas here.

For example I really like the onie_* family of GRUB functions.  It is nice to type `onie_rescue` from the GRUB prompt to boot into rescue mode.  I can see how that would be handy for automated testing -- I agree the GRUB menu is *painful* to deal with from automation.

I also think the changes for the DEMO-DIAG-OS are pretty good.  I can see the `diag_bootcmd` function as also being very useful from an automated testing perspective.  As the hardware vendor, you are responsible for both the ONIE implementation and the DIAG implementation.  Of course as part of that you need to test those components.  I am in favor of anything that helps you test your components.

Also I think it is fine that the DEMO-DIAG-OS reuse ONIE's GRUB -- it does not really need to install it's own GRUB.  Since the hardware vendor owns both ONIE and DIAG I see no problem there.

The changes to the DEMO-OS, however, go to far I think.  We need to maintain a clear separation between ONIE and the NOS.  The DEMO-OS is supposed to instruct NOS vendors "how to build an ONIE-compatible NOS installer".  The DEMO-OS is instructional.

The DEMO-OS *must* install and use its own GRUB, separate from ONIE.  That is the model.  That separation gives some freedom to the NOS vendor about how to build and integrate their OS.  Also most NOS do not simply install one GRUB menu entry (it would not be covered a single nos_menu variable).

I do not think we can predict exactly what each NOS vendor will do, so we should leave that part a bit open ended.

I understand that does not help your automated testing, but real life is like that.

Of course, you are free to implement your own DEMO OS for your own testing purposes.  It is just that the DEMO-OS that is in the upstream ONIE repo needs to be more generic.

With all that said -- cutting over to UEFI should make this easier.  No longer will the various OS's fight over who owns the GRUB.

**Comment by david56** [comment]
@cbrune, 

Thanks for reviewing the patchset.  I'll revise them.

> @mandeepsandhu said:
> +1 to this. I have seen this happen in our lab (thankfully it was only a test setup).
> 
> Maybe we can default to the least-destructive Rescue mode for the ONIE GRUB menu once it's installed on the system?

I noticed that Issue #174 ever talked about about GRUB.  It seems that the new approach should help it.

> Also most NOS do not simply install one GRUB menu entry (it would not be covered a single nos_menu variable).

About the NOS menu entries, I have further proposal in my head these days.  We can preserve several boot commands such as ``nos_bootcmd``, ``nos_bootcmd1``, ..., and ``nos_bootcmd9`` that would be similar to the role of ``ethaddr``, ``eth1addr``, ... in u-boot.

The new install approach *does not* force NOS installer to follow.  It just provides another optional usage for using.  With the new approach, NOS installer has a few various applications of GRUB.

- Present approach -- NOS *must* install and use its own GRUB.  NOS's GRUB is the first boot order.

It looks like:

    the 1st page:
    +---------------------------------------------+
    |*NOS menu 1         (boot NOS directly)      |
    | NOS menu 2         (boot NOS directly)      |
    | NOS menu 3         (boot NOS directly)      |
    | NOS menu 4         (boot NOS directly)      |
    | ONIE               (chainload to ONIE page) |
    |                                             |
    +---------------------------------------------+
    the 2nd page:
    +---------------------------------------------+
    |*ONIE: Install OS   (boot ONIE directly)     |
    | ONIE: Rescue       (boot ONIE directly)     |
    | ONIE: Uninstall OS (boot ONIE directly)     |
    | ONIE: Update ONIE  (boot ONIE directly)     |
    | ONIE: Embed ONIE   (boot ONIE directly)     |
    | DIAG menu          (chainload to DIAG page) |
    |                                             |
    +---------------------------------------------+
    the 3rd page:
    +---------------------------------------------+
    | DIAG menu          (boot DIAG directly)     |
    |*ONIE               (chainload to ONIE page) |
    |                                             |
    +---------------------------------------------+

- New approach -- NOS reuse ONIE's GRUB.  The GRUB has NOS boot commands.  ONIE's GRUB is the first boot order.

It looks like:

    the 1st page:
    +---------------------------------------------+
    |*NOS menu 1          (boot NOS directly)     |
    | NOS menu 2          (boot NOS directly)     |
    | NOS menu 3          (boot NOS directly)     |
    | NOS menu 4          (boot NOS directly)     |
    | ONIE: Install OS    (boot ONIE directly)    |
    | ONIE: Rescue        (boot ONIE directly)    |
    | ONIE: Uninstall OS  (boot ONIE directly)    |
    | ONIE: Update ONIE   (boot ONIE directly)    |
    | ONIE: Embed ONIE    (boot ONIE directly)    |
    | DIAG menu           (boot DIAG directly)    |
    |                                             |
    +---------------------------------------------+

- Hybrid approach -- NOS installs and uses its own GRUB.  NOS menu entry in ONIE page would chainload to NOS page.  ONIE's GRUB also has NOS boot commands that can boot NOS directly.  (NOS vendors ever asked us to add NOS menu entry in ONIE page that can for user go back to NOS page manually.)  This approach still leaves that part (you mentioned above) a bit open ended.

It looks like:

    the 1st page:
    +---------------------------------------------+
    |*NOS menu 1          (boot NOS directly)     |
    | NOS menu 2          (boot NOS directly)     |
    | NOS menu 3          (boot NOS directly)     |
    | NOS menu 4          (boot NOS directly)     |
    | ONIE                (chainload to ONIE page)|
    |                                             |
    +---------------------------------------------+
    the 2nd page:
    +---------------------------------------------+
    |*NOS menu            (chainload to NOS page) |
    | ONIE: Install OS    (boot ONIE directly)    |
    | ONIE: Rescue        (boot ONIE directly)    |
    | ONIE: Uninstall OS  (boot ONIE directly)    |
    | ONIE: Update ONIE   (boot ONIE directly)    |
    | ONIE: Embed ONIE    (boot ONIE directly)    |
    | DIAG menu           (boot DIAG directly)    |
    |                                             |
    +---------------------------------------------+

The later two approaches listed above also works find with UEFI case.  The NOS venders can choose one of them to fit thier requirement in real life.

Just some additional opinions.  How do you think?

**Comment by cbrune** [comment]
I hear what you are saying.  Thanks a lot for putting up these mock-ups of the GRUB menus.  It really helps to understand the ideas.

For the legacy BIOS systems I am very firm about the NOS installing and using its own GRUB.  ONIE is supposed to be dumb and simple.  Anything we do to make it "flexible" also makes it more complex, which leads to more bugs, a larger testing burden (for the HW vendors) and more user documentation and support.

The "new approach" described above I cannot support.  The problems are:
* all HW vendors (and ONIE certification) have to test *all* of the possibilities.  Some OS vendors may choose to install their own GRUB, some might not.  Doesn't matter to the HW vendor, they have to test *all* of the methods.  More work for all HW vendors!
* OS vendors would have choices to make.  How best to instruct them on which choice to make?  Which way should they build their installer, install their own GRUB or not?  More documentation.  More technical support.  More testing.

The "hybrid approach" described above is interesting.  It adds a little bit more complexity, but not much.  It is just as complex as the DIAG OS, which is already working pretty well.  Also it adds a very nice feature, having the "NOS menu" appear on the ONIE GRUB menu.  I think this is worth exploring.

[side note] -- it might be worth enhancing the DEMO OS installer to create more than one menu entry, more accurately simulating real life OS menus.  Perhaps add two entries, with different titles, that boot the same kernel+initrd with identical command line args.

My overall concerns about changing the legacy BIOS GRUB menus are:
* we have something that works today (it could be better I know)
* adding complexity (more testing, more bugs)
* changing existing customer workflows (they understand the current scheme)
* changing existing OS vendor workflows (they understand the current scheme)

I think the place to innovate and make these menus "better" is on the UEFI front.  The UEFI model makes installing multiple OS's easier to manage.  Also for the ONIE project no UEFI machines are shipping yet, so it is an opportunity to apply the lessons learned from the legacy BIOS method and make something better.  I would focus innovating energy on the UEFI model.

**Comment by david56** [comment]
I have revised the patchset.  The support of NOS boot commands and NOS reuses ONIE's GRUB feature are removed.

> According to the documentation, GRUB shell has a case statement which would be appropriate to use here.

I look it up in the document and source code.  I found ``case``, ``esac``, and ``select`` are just *reserved words*.  GRUB does not implement these statements.  So I keep it in ``if ... elif ... fi`` statement.

> Just for consistency I would add a onie_install fucntion.

I add the function and revise it to the menu entry.

> The "hybrid approach" described above is interesting. It adds a little bit more complexity, but not much. It is just as complex as the DIAG OS, which is already working pretty well. Also it adds a very nice feature, having the "NOS menu" appear on the ONIE GRUB menu. I think this is worth exploring.
> 
> [side note] -- it might be worth enhancing the DEMO OS installer to create more than one menu entry, more accurately simulating real life OS menus. Perhaps add two entries, with different titles, that boot the same kernel+initrd with identical command line args.

I'll spend time to do the two features:

- Have the "NOS menu" appear on the ONIE GRUB menu.
- Add two entries, with different titles, that boot the same kernel+initrd with identical command line args.

**Comment by cbrune** [comment]
This looks good to me.  Pushed to master:

- fbbd6ef grub: support DIAG boot command feeding
- 64bb47c grub: support u-boot-like ONIE boot commands

One thing you need to do before this is "complete" is to update the documentation on the ONIE wiki.

You can clone the wiki source like this:
```
git clone https://github.com/opencomputeproject/onie.wiki.git
```

[side note: github does not allow pull requests for the wiki repos.  it would be great if it did.  for this I think it would be good enough to send patches to the mailing list]

The following pages/sections need some update related to these changes:

- https://github.com/opencomputeproject/onie/wiki/Design-Spec-x86-Boot-Loader
I would add a section that describes the new "onie_xxx commands" that can be used from the GRUB prompt.

- https://github.com/opencomputeproject/onie/wiki/Design-Spec-x86-NOS-Interface#x86-nos-interface
The syntax of the `onie-boot-mode` command has changed.

- https://github.com/opencomputeproject/onie/wiki/Design-Spec-x86-NOS-Interface#x86-hardware-diagnostics-interface-optional
Review this entire section.  Definitely the `GRUB Considerations` sections needs to be updated.  Need to convey that ONIE DIAG behaviour changes from 2015.11 to 2016.02.

Need some words to indicate the behaviour changed:
```
For ONIE versions up to and including 2015.11 the diagnostic image 
installs GRUB into the MBR....
``` 

Then another paragraph or two that describe the new DIAG behaviour for 2016.02 and beyond.

Let's leave this PR open until the wiki documentation is updated.

**Comment by cbrune** [comment]
Closing this now that the wiki is updated with the new documentation.

**Pull request closed without merging**
