### PR TITLE
Update comments for CIG CS6436_56P

### PR DESCRIPTION
**Pull request by michealylj1**
I just update the comments for device CS6436_56P.

### CODE REVIEW

**Comment by ehdoyle** [comment]
Hi - if I'm understanding this correctly, the only real change here is commit  276e13f ?
If so, can this pull request be refactored ( or resubmitted ) to just have the one change? Otherwise the git history is going to be difficult to follow, and to be fair, I spent some time thinking the Add CIG commits were new platforms ( since the githashes were unique ) before looking at it a bit closer.

Thanks!

**Comment by michealylj1** [comment]
Sorry, I'm not clear about your suggestion. Please tell me how to update the comments which is my mistake.

Thanks,
Michael

**Comment by ehdoyle** [comment]
Sure. So if I understand the pull request, the only real change here is commit 276e13f ? If that is the case, I I could cherry pick that commit into the code, or you could generate a new pull request based off the current ONIE master that has just that change?
Thanks,
-Alex

**Comment by michealylj1** [comment]
Yes,  ony the change here is commit "276e13f". Please help me to do cherry pick into the code. 

Thanks,
Michael

**Comment by ehdoyle** [comment]
Hi - I pulled just that one change and merged it in. 
A rebuild with:
make -j32 MACHINEROOT=../machine/cig MACHINE=cig_cs6436_56p all
worked fine, so I'll close this out.  Let me know if anything looks incorrect.
Thanks!

**Pull request closed without merging**
