### PR TITLE
Accton AS4610 EEPROM: revise the size to fit hardware spec

### PR DESCRIPTION
**Pull request by david56**
The EEPROM on AS4610 is AT24C16D-SSHM-T 16Kb.

The patch has been tested in AS4610_54 and AS4610_30.

### CODE REVIEW

**Comment by vidyaravipati** [comment]
@david56 Following configuration is using 8 bit addressing to program eeproms which can cover max of 256 bytes.
#define CONFIG_SYS_I2C_EEPROM_ADDR_LEN      1       /* 8-bit addressing */

Qns:
a) Did you validate programming addresses greater than 256 in eeprom (>256, < 2048)
b) EEPROMs programmed with 8-bit and 16-bit are not compatible with each other . How are we planning to handle the boxes which are already released and programmed with 8 bits

**Comment by cbrune** [comment]
Vidya's second comment is the most worrisome.  The test case is this:

- boot board with old EEPROM size 
- write the EEPROM data
- install new ONIE with updated EEPROM size code
- read the EEPROM data

If the new code cannot read an EEPROM programmed using the old code then there's a problem.  That is a bad upgrade problem.

**Comment by david56** [comment]
@vidyaravipati @cbrune

**Comment by david56** [comment]
@vidyaravipati @cbrune  In u-boot, the iproc i2c driver uses ``page`` and ``offset`` to access EEPROM.  I traced u-boot source and found the following comments and codes.  It showes iproc i2c driver has capability to access EEPROM over 256 bytes in 8-bit addressing mode.

Comments:

    * for CONFIG_SYS_I2C_EEPROM_ADDR_LEN == 1 (8-bit EEPROM page address) offset is
    *   0x00000nxx for EEPROM address selectors and page number at n.
    ...
    * EEPROM -- AS4610 uses a 16Kbit I2C EEPROM (AT24C16C-SSHM-T)
    * I2C address 0x50 - 0x57, sitting begind a PCA9548 mux at 
    * I2C address 

Codes:

    #if CONFIG_SYS_I2C_EEPROM_ADDR_LEN == 1 && !defined(CONFIG_SPI_X)
		uchar addr[2];

		blk_off = offset & 0xFF;	/* block offset */

		addr[0] = offset >> 8;		/* block number */
		addr[1] = blk_off;		/* block offset */
		alen	= 2;
    #else 
    ...
    #endif	/* CONFIG_SYS_I2C_EEPROM_ADDR_LEN, CONFIG_SPI_X */

		addr[0] |= dev_addr;		/* insert device address */

		len = end - offset;
    ...
		if (i2c_read (addr[0], offset, alen-1, buffer, len) != 0)
			rcode = 1;

I just did the test case said by Curt.  Please check the log:

https://gist.github.com/david56/0c1cb0f02a20890b3328

**Comment by vidyaravipati** [comment]
Looks good for me

**Comment by cbrune** [comment]
Pushed to master:

- 1066860 Accton AS4610 EEPROM: revise the size to fit hardware spec

**Pull request closed without merging**
