### PR TITLE
Add FTS to uclibc and mtree utility (for NOS checks)

### PR DESCRIPTION
**Pull request by cobracmder**
For testing use:
```
ONIE_MIRROR = http://104.131.140.22/onie
CROSSTOOL_ONIE_MIRROR = http://104.131.140.22/onie/crosstool-NG
```
as the _mtree_ tarball is located there.

For size comparisons, I have used three platforms: as4600, as5712, and as6700.

## as4600

Filename | du -sk (FTS) | du -sk (unchanged) | delta (KB)
-------------|-----------------|---------------------------|-------------
accton_as4600_54t-r0.dtb  | 8 | 8 | 0
accton_as4600_54t-r0.initrd | 1048 | 1048 | 0
accton_as4600_54t-r0.itb | 3836 |  3836 | 0
accton_as4600_54t-r0.u-boot | 512 | 512 | 0
onie-accton_as4600_54t-r0.bin | 4160 | 4160 | 0
onie-accton_as4600_54t-r0.bin.uboot | 512 | 512 | 0
onie-updater-powerpc-accton_as4600_54t-r0 | 3984 | 3984 | 0 
sysroot.cpio | 3268 | 3260 | 8

## as5712

Filename | du -sk (FTS) | du -sk (unchanged) | delta (KB)
-------------|-----------------|---------------------------|-------------
accton_as5712_54x-r0.initrd | 5284 | 5280 | 4
accton_as5712_54x-r0.vmlinuz | 3348 | 3348 | 0
onie-recovery-x86_64-accton_as5712_54x-r0.iso | 18432 | 18432 | 0
onie-updater-x86_64-accton_as5712_54x-r0 | 8652 | 8644 | 8
recovery-x86_64-accton_as5712_54x-r0.initrd | 13900 | 13892 | 8
sysroot.cpio | 22620 | 22616 | 4

## as6700

Filename | du -sk (FTS) | du -sk (unchanged) | delta (KB)
-------------|-----------------|---------------------------|-------------
accton_as6700_32x-r1.dtb | 32 | 32 | 0
accton_as6700_32x-r1.initrd | 1048 | 1048 | 0
accton_as6700_32x-r1.itb | 4504 | 4500 | 4
accton_as6700_32x-r1.u-boot | 548 | 548 | 0
onie-accton_as6700_32x-r1.bin | 5376 | 5376 | 0
onie-accton_as6700_32x-r1.bin.uboot | 548 | 548 | 0
onie-updater-powerpc-accton_as6700_32x-r1 | 4684 | 4672 | 12
sysroot.cpio | 3268 | 3260 | 8

### CODE REVIEW

**Comment by david56** [comment]
Thanks.  It looks the sizes are very close to original ones.  I was worried about the ONIE itb image size which may be larger than the ONIE partition size in AS5600_52X and AS5610_52X (``3538944`` bytes; ``0x360000`` in hex)

**Comment by david56** [comment]
Current image sizes are:

    3505764 Jan 15 16:02 accton_as5600_52x-r0.itb
    3522692 Mar 17 16:09 accton_as5610_52x-r0.itb

**Comment by cobracmder** [comment]
Just so we can compare apples to apples (I'll perform this same comparison for the 5600 and 5610 tomorrow so we have the numbers).

## as4600

Filename | ls -l (FTS) | ls -l (unchanged) | delta (B)
-------------|-----------------|---------------------------|-------------
accton_as4600_54t-r0.dtb  | 6928  | 6928 | 0
accton_as4600_54t-r0.initrd | 1072592 | 1070072 | 2520
accton_as4600_54t-r0.itb | 3927704 | 3925180 | 2524
accton_as4600_54t-r0.u-boot | 524288 | 524288 | 0
onie-accton_as4600_54t-r0.bin | 4259840 | 4259840 | 0
onie-accton_as4600_54t-r0.bin.uboot | 524288 | 524288 | 0
onie-updater-powerpc-accton_as4600_54t-r0 | 4077281 | 4077281 |  0
sysroot.cpio | 3342848  | 3334656 | 8192

## as5712

Filename | ls -l (FTS) | ls -l (unchanged) | delta (B)
-------------|-----------------|---------------------------|-------------
accton_as5712_54x-r0.initrd | 5408780 | 5404596 | 4184
accton_as5712_54x-r0.vmlinuz | 3425760 | 3425760 | 0
onie-recovery-x86_64-accton_as5712_54x-r0.iso | 18874368 | 18874368 | 0
onie-updater-x86_64-accton_as5712_54x-r0 | 8859361 | 8849121 | 10240
recovery-x86_64-accton_as5712_54x-r0.initrd | 14230632 | 14222196 | 8436
sysroot.cpio | 23159296  | 23155200 | 4096

## as6700

Filename | ls -l (FTS) | ls -l (unchanged) | delta (B)
-------------|-----------------|---------------------------|-------------
accton_as6700_32x-r1.dtb | 29297 | 29297 | 0
accton_as6700_32x-r1.initrd | 1072508 | 1070092 | 2416
accton_as6700_32x-r1.itb | 4610292 | 4607868 | 2424
accton_as6700_32x-r1.u-boot | 557872 | 557872 | 0
onie-accton_as6700_32x-r1.bin | 5505024 | 5505024 | 0
onie-accton_as6700_32x-r1.bin.uboot | 557872 | 557872 | 0
onie-updater-powerpc-accton_as6700_32x-r1 | 4794081 | 4783841 | 10240
sysroot.cpio | 3342848 | 3334656 | 8192

**Comment by cobracmder** [comment]
Here are the numbers for as5600 and as5610.

## as5600

Filename | ls -l (FTS) | ls -l (unchanged) | delta (B)
-------------|-----------------|---------------------------|-------------
accton_as5600_52x-r0.dtb | 18351 | 18351 | 0
accton_as5600_52x-r0.initrd | 741740 | 739768 | 1972
accton_as5600_52x-r0.itb | 3524648 | 3522680 | 1968
accton_as5600_52x-r0.u-boot | 524288 | 524288 | 0
onie-accton_as5600_52x-r0.bin | 3604480 | 3604480 | 0
onie-accton_as5600_52x-r0.bin.uboot | 524288 | 524288 | 0
onie-updater-powerpc-accton_as5600_52x-r0 | 3657441 | 3657441 | 0
sysroot.cpio | 2111488 | 2103296 | 8192

## as5610

Filename | ls -l (FTS) | ls -l (unchanged) | delta (B)
-------------|-----------------|---------------------------|-------------
accton_as5610_52x-r0.dtb | 18351 | 18351 | 0
accton_as5610_52x-r0.initrd | 741804 | 739516 | 2288
accton_as5610_52x-r0.itb | 3524580 | 3522296 | 2284
accton_as5610_52x-r0.u-boot | 524288 | 524288 | 0
onie-accton_as5610_52x-r0.bin | 3604480 | 3604480 | 0
onie-accton_as5610_52x-r0.bin.uboot | 524288 | 524288 | 0
onie-updater-powerpc-accton_as5610_52x-r0 | 3657441 | 3657441 | 0
sysroot.cpio | 2111488 | 2103296 | 8192

**Comment by cbrune** [comment]
Thanks for the data @cobracmder.  I'll let @david56 give the final OK, but it looks like the .itb sizes for AS5600 and AS5610 are *just* barely under 3538944 bytes (`0x360000` in hex).  Looks OK.

Will wait for @david56 .

**Comment by david56** [comment]
Thank you very much.  It looks OK to me.

**Comment by cbrune** [comment]
pushed to master:

- 5cfd81b Add mtree utility
- 671a2be Add FTS to uclibc

**Comment by cbrune** [comment]
In regression builds I am see failures due to the image size on accton_as5600_52x:
```
...
==== Create accton_5652-r0 ONIE binary image ====
ERROR: /work/monster-04/onie-build/ci/master/onie/build/images/accton_5652-r0.itb size (3539556) is greater than max size: 3538944
make[1]: *** [/work/monster-04/onie-build/ci/master/onie/build/accton_5652-r0/stamp/image-bin] Error 1
...
```

Looks like we are right on the of being too large.  Guessing some build host differences influence the file size -- perhaps depth of directory tree, date, time, compression random seed, etc. can influence the final image size +/- 1000 bytes or so.

I don't think this is going to work as is...

**Comment by cobracmder** [comment]
womp, womp :frowning: 

Any thoughts on reducing the size (besides stripping symbols, etc...)?

**Comment by cbrune** [comment]
Actually I made a mistake with my build.  I think this is OK. Closing.

**Pull request closed without merging**
