### PR TITLE
[Netberg][nba221] Aurora 221 initial support

### PR DESCRIPTION
**Pull request by andrewsapronov**
Could you please merge support for Trident 3 based Netberg Aurora 221 switch:

-  48x 1G BASE-T, 8x 10G SFP+ ,
-  Broadcom Trident 3 Broadcom BCM56275
-  CPU Denverton-NS C3508 4-Core
-  8GB DDR4 ECC

### CODE REVIEW

**Comment by mshych** [comment]
Thank you. Commit is merged to master.

**Comment by andrewsapronov** [comment]
@mshych could you please check the PR. Commit  seems to be unmerged.

**Comment by andrewsapronov** [comment]
@mshych could you please merge this closed PR

**Comment by mshych** [comment]
Hi, sorry mixed it with your PR for machine/netberg/netberg_aurora_621
I'll do Wednesday.  Thx.

**Pull request merged**
