### PR TITLE
Alphanetworks platforms: change the vendor name to follow naming conventions

### PR DESCRIPTION
**Pull request by willkuo103**

### CODE REVIEW

**Comment by cbrune** [comment]
Looks OK.

pushed to master:

- 60d7cb5 AlphaNetworks platforms: change the vendor name

**Comment by cbrune** [comment]
I this file also needs a rename:

contrib/autobuild/config/alpha_networks_snx60a0_486f.json

**Comment by willkuo103** [comment]
Hi Curt,

I have modified the config file "contrib/autobuild/config/alpha_networks_snx60a0_486f.json" and change the vendor name string in the file.

Thanks,
Will

**Comment by cbrune** [comment]
Looks good.  Pushed to master:

- 7a04d73 Aphanetworks: Modify vendor name for DUT configuration file.

**Pull request closed without merging**
