### PR TITLE
Updating e2fsprogs to 1.44.5 in order to support metadata_csum for ext4

### PR DESCRIPTION
**Pull request by rkandilarov**
The current fsck.ext4 version (1.43) does not support metadata_csum so update to Debian Buster version (1.44.5). More info at https://github.com/opencomputeproject/onie/issues/912 .

### CODE REVIEW

**Comment by ehdoyle** [comment]
Hi - sorry for taking so long to get back to this. 
I'm working on component updates, and I'm not seeing errors around e_error_block not being defined. Although I'm using a 4.19 kernel, crosstool-ng version 24 (vs 23) and the 1.45.6 version of e2fsprogs ( which built just by updating the version and adding the --disable-nls option in e2fsprogs.make (and thank you for that in the patch, as it saved me some time in running it down.)

So I'm wondering if the latest version may just work?

**Comment by paulmenzel** [comment]
In what branch is your work with e2fsprogs 1.45.6?

**Comment by paulmenzel** [comment]
(And if there was a commit, it looks like you didn’t reference issue https://github.com/opencomputeproject/onie/issues/912.

**Comment by ehdoyle** [comment]
Hi - sorry again about the delay on this. The master branch just got upgraded to 1.46.3 of e2fsprogs - does that fix the issues you were seeing?

**Comment by ehdoyle** [comment]
Closing out as part of bug cleanup. I'm expecting version 1.46.3 in the master branch should have the fix.

**Pull request closed without merging**
