### PR TITLE
Stordis_bf2556x_1t switch porting.

### PR DESCRIPTION
**Pull request by kamalkrbh**

### CODE REVIEW

**Comment by ehdoyle** [comment]
Hi - I think you inadvertently deleted the demo/platform.conf file that gets used building the 'demo' target from the command line. I'm trying a reproduction build with that restored, using the build targets:
all recovery-iso demo
The demo target was failing build when it went to copy that file.  Apart from that, things are looking good.

**Comment by ehdoyle** [comment]
Hm. On a clean checkout I'm getting a build error trying to apply kernel patch 0001 - possibly related to something from this patch, as I did get the 'all' target to build prior to that addition.

Thoughts?
Thanks,
-Alex

Patch?
https://github.com/opencomputeproject/onie/pull/880/commits/2ee78067b51d6077badeb43b190d98c86d2bc9cb
Build invoked with:
 make -j1 MACHINEROOT=../machine/stordis MACHINE=stordis_bf2556x_1t all

Here's the error message:
==== Getting Linux ====                                                                                                                                                                                                                                       
  Downloading linux-4.9.95.tar.xz from: http://mirror.opencompute.org/onie/linux-4.9.95.tar.xz                                                                                                                                                                
2019-12-11 20:28:52 URL:http://mirror.opencompute.org/onie/linux-4.9.95.tar.xz [93289700/93289700] -> "/home/adoyle/ONIE/stordis/onie/build/download/linux-4.9.95.tar.xz" [1]                                                                                 
  Got          linux-4.9.95.tar.xz                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              
linux-4.9.95.tar.xz: OK                                                                                                                                                                                                                                       
==== Extracting Linux ====                                                                                                                                                                                                                                    
==== patching  Linux ====                                                                                                                                                                                                                                     
Initialized empty Git repository in /home/adoyle/ONIE/stordis/onie/build/stordis_bf2556x_1t-r0/kernel/linux-4.9.95/.git/                                                                                                                                      
Checking for changes in the working directory ... done                                                                                                                                                                                                        
stg import: [Errno 2] No such file or directory:                                                                                                                                                                                                              
            '/home/adoyle/ONIE/stordis/onie/build/stordis_bf2556x_1t-r0/kernel/patch/0001                                                                                                                                                                     
            -igb-remove-abnormal-reset.patch'                                                                                                                                                                                                                 
make/kernel.make:68: recipe for target '/home/adoyle/ONIE/stordis/onie/build/stordis_bf2556x_1t-r0/stamp/kernel-patch' failed                                                                                                                                 
make: *** [/home/adoyle/ONIE/stordis/onie/build/stordis_bf2556x_1t-r0/stamp/kernel-patch] Error 2

**Comment by kamalkrbh** [comment]
Thanks @ehdoyle for review, 
To address above comments :
Patch related issue - Added missing new line at the end of the file kernel/series,
Demo target build - Added demo/platform.conf file for building demo target.
Now able to build targets - all recovery-iso demo

**Comment by ehdoyle** [comment]
Excellent - everything built great. I squashed the commits to make sure that any checkout gets the code in its current state. Thanks for working through the revisions on the submission.

**Pull request closed without merging**
