### PR TITLE
Add recent Accton platforms to support ONIE.

### PR DESCRIPTION
**Pull request by david56**
Add recent Accton platforms to support ONIE.
They are:

- AS5812_54T
- AS5812_54X
- AS6812_32X

### CODE REVIEW

**Comment by cbrune** [comment]
Generally these look OK, but there are a few documentation issues:

- the commit messages should be more descriptive.  For example, what is a AS5812_54T? AS5812_54X? AS6812_32X?
- the INSTALL file for each machine is missing information about how to install the software

**Comment by david56** [comment]
Updated.  Thank you.

**Comment by david56** [comment]
The work around has been removed in the updated commits.

**Comment by david56** [comment]
Updated.  Please review them again.  Thanks.

**Comment by cbrune** [comment]
Great, thanks! Pushed to master:

- b580c46 Accton AS6812_32X: add to support ONIE
- 36a3de1 Accton AS5812_54X: add to support ONIE
- 2cb0a96 Accton AS5812_54T: add to support ONIE

**Pull request closed without merging**
