### PR TITLE
Wnc 20150703

### PR DESCRIPTION
**Pull request by vic1231**
sst1-n1, modify eeprom access rules and change console speed to 57600.

### CODE REVIEW

**Comment by cbrune** [comment]
2 of the commits in the PR have been applied previously.

You should make a new PR for the new changes.

Also for the new changes please make separate commits for each logical idea -- do not mix i2c changes and console baud rate changes into a single commit.  The project patch policy is described here:

https://github.com/opencomputeproject/onie/wiki/Contributing#general-patching-philosophy

I am closing this PR as you need to make a new one after the above items are cleared up.

**Comment by vic1231** [comment]
Hi Curt:
I'm not well understand of "make a new PR", it means new branch?
Shall I get latest version(include my pulled codes), and set a branch, then make an PR?
And also delete this PR successful branch?

**Comment by cbrune** [comment]
A new PR means a new branch.  Once a PR is accepted "pulled in" the branch is no longer needed.  These articles are useful:

https://help.github.com/articles/using-pull-requests/ (we use the "fork and pull" model)

After you fork from the main repo, your fork will start to get out of date with respect to main repo master branch.  Before working on a new topic branch (a new PR) you should bring your local fork up to date with the main repo.  These articles cover this topic:

https://help.github.com/articles/syncing-a-fork/
https://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

Distilling those articles a bit. You need to do the following.

One time you have to configure a remote 'upstream' branch for your local fork.  Do this:
```
linux:$ git remote add upstream https://github.com/opencomputeproject/onie.git
linux:$ git remote -v
```

For my local fork `git remote -v` prints the following:
```
origin	git@github.com:cbrune/onie.git (fetch)
origin	git@github.com:cbrune/onie.git (push)
upstream	https://github.com/opencomputeproject/onie.git (fetch)
upstream	https://github.com/opencomputeproject/onie.git (push)
```

`origin` is my personal fork of the ONIE repo.  `upstream` is the main repo.  Yours would look similar, but the `origin` would point at your github account.

You only have to setup the `upstream` once.

Now over time opencomputeproject/onie.git diverges from cbrune/onie.git (gets behind).  To bring my local fork up to date with the upstream do this:
```
linux:$ git checkout master
linux:$ git fetch upstream
linux:$ git merge upstream/master
```

Now your local fork is up to date with the main repo.

Once your fork's master branch is up to date then you can start work on the new topic branch.  For example say I want to work on feature XYZ -- Once my fork's master it up to date I use a command like this:
```
linux:$ git checkout -b XYZ
Switched to a new branch 'XYZ'
```

That creates a new branch `XYZ` based on master and checks it out.

Then when I want to make a PR I push my topic branch to my personal ONIE repo:
```
linux:$ git push origin XYZ
```

When are all done with a PR you can delete the topic branch:
https://help.github.com/articles/deleting-unused-branches/

**Comment by vic1231** [comment]
Hi Curt:
Thanks, it's helpful. Will try that.


2015-07-17 23:57 GMT+08:00 Curt Brune <notifications@github.com>:

**Pull request closed without merging**
