### PR TITLE
Ufi 20210507

### PR DESCRIPTION
**Pull request by jaytclin**
Update 3 projects: ufispace_s9700_23d, ufispace_s9700_53dx, ufispace_s9705_48d

Add 15 projects: 
1. S9300-32D
Switch ASIC: Broadcom BCM56880 (32 x 400GbE QSFPDD ports,  2 x 10GbE SFP+ ports, )
CPU: Intel Skylake-D, D-2145NT (8 cores/ 1.9 GHz)
Management: 2 x 10G SFP+, 1 x GbE OOB management port
Console: ttyS0

2. S9310-32D
Switch ASIC: Broadcom BCM56880 (32 x 400GbE QSFPDD ports,  4 x 10GbE SFP+ ports, )
CPU: Intel Skylake-D, D-2145NT (8 cores/ 1.9 GHz)
Management: 2 x 10G SFP+, 1 x GbE OOB management port
Console: ttyS0

3. S9500-22XST
Switch ASIC: Broadcom Qumran-AX BCM88470 (4 x 10/100/1000 Base-T ports, 8 x 10GbE SFP+ ports, 8 x 25GbE SFP28 ports, 2 x 100GbE QSFP28 ports)
CPU: CPU Broadwell-DE D-1519 with quad core @ 1.5GHz
Management: 1 x GbE OOB management port
Console: ttyS0

4. S9501-16SMT: 
Switch ASIC: Broadcom BCM88273 (4x 10GbE SFP+ ports, 8x 2.5GbE SFP ports, 4x GbE RJ45 ports) 
CPU: Intel Denverton-NS C3308 (2 cores/ 1.6 GHz) 
Management: 1x RJ45 console, 1x GbE OOB management port
Console: ttyS0

5. S9501-18SMT: 
Switch ASIC: Broadcom BCM88272 (6x 10GbE SFP+ ports, 8x 2.5GbE SFP ports, 4x GbE RJ45 ports) 
CPU: Intel Denverton-NS C3508 (4 cores/ 1.6 GHz) 
Management: 1x RJ45 console, 1x GbE OOB management port
Console: ttyS0

6. S9501-28SMT: 
Switch ASIC: Broadcom BCM88270 (8x 10GbE SFP+ ports, 16x 2.5GbE SFP ports, 4x GbE RJ45 ports) 
CPU: Intel Denverton-NS C3508 (4 cores/ 1.6 GHz) 
Management: 1x RJ45 console, 1x GbE OOB management port
Console: ttyS0

7. S9510-28DC
Switch ASIC: Broadcom Qumran-2a BCM88483 (2-port 400GE QSFPDD, 2-port 100GE QSFP28, 24-port 25GE SFP28)
CPU: CPU Denverton-NS C3708 8-Core @ 1.7GHz
Management: 1 x GbE OOB management port
Console: ttyS0

8. S9510-30XC
Switch ASIC: Broadcom Qumran-2u BCM88284 (2-port 100GE QSFP28, 28-port 25GE SFP28)
CPU: CPU Denverton-NS C3508 4-Core @ 1.6GHz
Management: 1 x GbE OOB management port
Console: ttyS0

9. S9600-32XC
Switch ASIC: Broadcom BCM88820 (32 x 100GbE QSFP28 + 4 x 25 GbE SFP28(In-band port with 100GbE P00))
CPU: Intel Xeon D-2145NT  (8 cores/ 1.9 GHz)
Management: 1 x GbE OOB management port
Console: ttyS0

10. S9600_48X:
Switch ASIC: Broadcom BCM88690 (48 x 100GbE QSFP28 ports)
CPU: Intel Broadwell-DE D-1548 (8 cores/ 2.0 GHz)
Management: 2 x 10G SFP+, 1 x GbE OOB management port
Console: ttyS0

11. S9600-64XC
Switch ASIC: Broadcom BCM88820 x2 (64 x 100GbE QSFP28 + 4 x 25 GbE SFP28(In-band port with 100GbE P00))
CPU: Intel Xeon D-2145NT  (8 cores/ 1.9 GHz)
Management: 1 x GbE OOB management port
Console: ttyS0

12. S9600-72XC
Switch ASIC: Broadcom BCM88820 (64 x 25GbE SFP28 ports, 8 x 100GbE QSFP28 ports)
CPU: Intel Xeon D-2145NT  (8 cores/ 1.9 GHz)
Management: 2 x 10G SFP+, 1 x GbE OOB management port
Console: ttyS0

13. S9701-78DC
Switch ASIC: Broadcom BCM88820 (64 x 25GbE SFP28 ports, 8 x 100GbE QSFP28 ports)
CPU: Intel Xeon D-2145NT  (8 cores/ 1.9 GHz)
Management: 2 x 10G SFP+, 1 x GbE OOB management port
Console: ttyS0

14. S9701-82DC
Switch ASIC: Broadcom BCM88802 (64 x 25GbE SFP28 ports, 12 x 100GbE QSFP28 ports,  6 x 400GbE QSFPDD ports)
CPU: Intel Xeon D-2145NT  (8 cores/ 1.9 GHz)
Management: 2 x 10G SFP+, 1 x GbE OOB management port
Console: ttyS0

15. S9710-76D:
Switch ASIC: Broadcom BCM88850 (36x400GbE NIF QSFPDD ports, 40x400GbE Fabric QSFPDD ports)
CPU: Intel Xeon D-2145NT  (8 cores/ 1.9 GHz)
Management: 2x10G SFP+, 1xGbE OOB management port
Console: ttyS0

### CODE REVIEW

**Comment by billie-alsup** [comment]
Is it really necessary to have a different build for each of these machines?  Is there no way you can determine at runtime the machine type?  If you're bringing up 15 machines at once, it seems there must be a lot of commonality between them.  I'd hope that you could differentiate them via an EFI variable, or something in an EEPROM or flash, etc.  You can then have a single ONIE image that covers the entire "family" of machines.  There is a difference between a build machine.conf and a runtime machine.conf.  the build machine.conf can then be the family, and once you dynamically determine the machine (again, if that is possible), then you generate the runtime machine.conf via the sysroot-lib-onie/gen-config-platform script which should define the function gen_live_config().  there is no requirement that there be a distinct onie build for every machine.  it seems like a very difficult approach to maintain long term.

**Comment by jaytclin** [comment]
Hi sir, 
Thanks for your good suggestion.
But yes, we do need a "machine" folder for different machines. 
According to our experiences, we have different customers for the machines.
Each customer may have their requests for some features on different machines.
In that case, even if some machines belong to the same family, the code/config may vary according to different customers.
In addition, we will also have ONIE firmware updater requirements for each project.
The firmware/ HW components and tools for each platform will be different, too.
That's why we need so many machines.

Thank you.

**Comment by jaytclin** [comment]
Hi Sir,

We may start to consider to investigate about your suggestions, but before that our partners and customers taking different projects need the source code for their projects in current development stage.
Also, if we start to integrate to one machine for a whole family, then we will have to consider the following cases first:
1. Whenever a project needs a new feature, the source code changes and the vendor version updates. However, other projects don't need that feature, but the code/version is changed. The one who is going to build the code will have to go through the all release notes to see what change is needed for the specific project.
2. As I mentioned, we have several partners and customers. Customers taking project A does not need/want to know or integrate the changes of project B C D ... and so on. In this case, separating the machines will be better.

**Comment by ehdoyle** [comment]
Weighing in as Project Lead here, I really appreciate Billie raising the platform consolidation option with wording that was much clearer than I'd have been able to provide, saving me time of asking those questions and the embarrassment of phrasing them poorly, as that was the first thing I'd thought as well.
Looking at the thread so far, I think that jaytclin since has confirmed that consolidation was considered, but they have reasons for doing it this way, and that the burden of code maintenance for a platform  falls largely on the manufacturer (at least, that's traditionally where I have seen most updates coming from), I'm inclined to accept the pull request.
I'm mentioning this now since  it will probably be while before I actually get to merging the code, given the size of the submission, and the fact that it is really encouraging me to start the acceptance process by fixing a bug I had in my Jenkins code that rebuilds every ONIE target.
'cause it looks like I'm gonna need it :)

**Comment by ehdoyle** [comment]
Hi - just started looking at this. What is the role of the release version file at: build-config/conf/onie-release?
[link](https://github.com/opencomputeproject/onie/pull/958/commits/2a7e33e2cf0b88312f6cf16a664d23b1c9db1242)
I'm planning on running test builds on the platforms over the weekend.
Thanks!

**Comment by jaytclin** [comment]
Hi Alex, 
We'll create another pull request to correct this, thanks.

**Pull request closed without merging**
